apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      # List of all the directories we wanna sync
      - ./infra/k8s/*
build:
  # When we build image don't try to push at docker hub
  local:
    push: false
  # All the things that are going to build.
  artifacts:
    - image: nasir/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      # How to handle any files to change
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
