openapi: 3.0.0

info:
  description: |
    API specification of Ticketing App.
  version: "1"
  title: Ticketing API

servers:
  - url: "https://ticketing.dev/api"
    description: Auth service.

paths:
  # users
  /users/signup:
    $ref: "./users/users.yml"
